# This file was generated by GoReleaser. DO NOT EDIT.
cask "mail-muncher" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "643f9af590fce2c12f205a1e99d5f2d7c781372d9d27d29880caebbb0d479945"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d1cd9d28e3224ea1ef363c664ab5229f7ec50ae4ac71d4f19f9d384b809bc3b"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d929726ab4a50d71a8bd00edde617bd7eed1e6d900c69c07f49726bd8fd2a8f"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6eb1911bfd471b21dece92d5fcbb2d33ca4a49225cebe10b6d2fb2958b93a2f3"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mail-muncher"
  desc "An email client for AI agents -- filtered, read-only Gmail delivered to disk as .eml + markdown, and served over MCP."
  homepage "https://github.com/craigjmidwinter/mail-muncher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mail-muncher"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mail-muncher"]
    end
  end

  # No zap stanza required

end
