# This file was generated by GoReleaser. DO NOT EDIT.
cask "mail-muncher" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "3bb3737727f62366e5878a008dcf77793eb9857b492d5fa5f75e592cf4e621a6"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60a0f90ea6e953942aa226a522f0d94dfeb0dfaec71568cdfa9e17841c347129"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "87889dfa90d08f07ed7f02e54684fa681aac16ea232f91b940e827afe76bcb11"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "58dffd451e87ead1b104556146e842eecb594d10a46e7cd5cd80056c29db3f68"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mail-muncher"
  desc "An email client for AI agents -- filtered, read-only Gmail delivered to disk as .eml + markdown, and served over MCP."
  homepage "https://github.com/craigjmidwinter/mail-muncher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mail-muncher"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mail-muncher"]
    end
  end

  # No zap stanza required

end
