# This file was generated by GoReleaser. DO NOT EDIT.
cask "mail-muncher" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f78acd4aa433fb15fb0d6386b0ad99452b00c820e8a26aa4440e167ea20e5f7b"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a167f2733b2528678d7795135a55bd303b416bb70de0f24023fbb4cc68bc465f"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d695ffe4e65cef24b3aaeb6d71a05e45673bf3cafb2f69da54e532d27619c30"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "06898f7241468abb7eb725e208cb378626b3bc4a93bdfe302991f8f4db3a7cd2"
      url "https://github.com/craigjmidwinter/mail-muncher/releases/download/v#{version}/mail-muncher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mail-muncher"
  desc "An email client for AI agents -- filtered, read-only Gmail delivered to disk as .eml + markdown, and served over MCP."
  homepage "https://github.com/craigjmidwinter/mail-muncher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mail-muncher"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mail-muncher"]
    end
  end

  # No zap stanza required

end
